// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"database/sql"
	"time"
)

type User struct {
	IDUser    int32        `json:"idUser"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	CreatedOn time.Time    `json:"createdOn"`
	LastLogin sql.NullTime `json:"lastLogin"`
}
