// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"context"
)

type Querier interface {
	GetUserById(ctx context.Context, idUser int32) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
