---

# server
PORT: "8080"
#SERVER_SSL_ENABLED: true
#SERVER_READ_TIMEOUT: 10s
#SERVER_WRITE_TIMEOUT: 10s
#SERVER_IDLE_TIMEOUT: 30s

# service
SERVICE_NAMESPACE: go-microservice
SERVICE_NAME: starter
SERVICE_VERSION: 0.2.0

# logger
LOGGER_LEVEL: info

# database
DB_HOST: ec2-52-3-2-245.compute-1.amazonaws.com
DB_PORT: 5432
DB_USER: nhvkdzndolwcny
DB_PASSWORD: <env>
DB_DBNAME: d3f5q8p0bd4qnm
