---
SERVER_PORT: ":8443"
SERVER_SSL_ENABLED: true
SERVER_READ_TIMEOUT: 10s
SERVER_WRITE_TIMEOUT: 10s
SERVER_IDLE_TIMEOUT: 30s

SERVICE_NAMESPACE: domain-subdomain
SERVICE_NAME: newservice
SERVICE_VERSION: 0.0.1