---

# server
SERVER_PORT: ":8888"
#SERVER_SSL_ENABLED: true
#SERVER_READ_TIMEOUT: 10s
#SERVER_WRITE_TIMEOUT: 10s
#SERVER_IDLE_TIMEOUT: 30s

# service
SERVICE_NAMESPACE: go-microservice
SERVICE_NAME: starter
SERVICE_VERSION: 0.1.0

# logger
LOGGER_LEVEL: info

# database
DB_HOST: 127.0.0.1
DB_PORT: 5433
DB_USER: postgres
DB_PASSWORD: <env>
DB_DBNAME: postgres
