---

# server
PORT: "8080"
SERVER_READ_TIMEOUT: 10s
SERVER_WRITE_TIMEOUT: 10s
SERVER_IDLE_TIMEOUT: 30s
#SERVER_SSL_ENABLED: true

# service
SERVICE_NAMESPACE: go-microservice
SERVICE_NAME: starter
SERVICE_VERSION: 0.2.0

# logger
LOGGER_LEVEL: info

# database
DB_HOST: ec2-52-3-2-245.compute-1.amazonaws.com
DB_PORT: 5432
DB_USER: nhvkdzndolwcny
DB_PASSWORD: <env>
DB_DBNAME: d3f5q8p0bd4qnm
DB_CONN_MAX_LIFETIME: 3m
DB_MAX_OPEN_CONNS: 10
DB_MAX_IDLE_CONNS: 10
